const countryList = {
    "AED-UAE Dirham" : "AE",
    'AFN-Afghan Afghani': "AF",
    'ALL-Albanian Lek': "AL",
    'AMD-Armenian Dram': "AM",
    'ANG-Netherlands Guilder': "CW",
    'AOA-Angolan Kwanza': "AO",
    'ARS-Argentine Peso': "AR",
    'AUD-Australian Dollar': "AU",
    'AWG-Aruban Florin': "AW",
    'AZN-Azerbaijani Manat': "AZ",
    'BAM-Bosnia ': "BA",
    'BBD-Barbadian Dollar': "BB",
    'BDT-Bangladeshi Taka': "BD",
    'BYN-Belarusian Ruble': "BY",
    'BZD-Belize Dollar': "BZ",
    'BMD-Bermudian Dollar': "BM",
    'BND-Brunei Dollar': "BN",
    'BOB-Bolivian Boliviano': "BO",
    'BRL-Brazilian Real': "BR",
    'BSD-Bahamian Dollar': "BS",
    'BTN-Bhutanese Ngultrum': "BT",
    'BWP-Botswanan Pula': "BW",
    'BYR-Belarusian Ruble': "BY",
    'BZD-Belize Dollar': "BZ",
    'CAD-Canadian Dollar': "CA",
    'CDF-Congolese Franc': "CD",
    'CHF-Swiss Franc': "CH",
    'CLF-Chilean Fomento': "CL",
    'CLP-Chilean Peso': "CL",
    'CNY-Chinese Yuan': "CN",
    'COP-Colombian Peso': "CO",
    'CRC-Costa Rican Colón': "CR",
    'CUP-Cuban Peso': "CU",
    'CVE-Cape Verdean ': "CV",
    'CZK-Czech Koruna': "CZ",
    'DJF-Djiboutian Franc': "DJ",
    'DKK-Danish Krone': "DK",
    'DOP-Dominican Peso': "DO",
    'DZD-Algerian Dinar': "DZ",
    'EGP-Egyptian Pound': "EG",
    'ERN-Eritrean Nakfa': "ER",
    'ETB-Ethiopian Birr': "ET",
    'EUR-Euro': "EU",
    'FJD-Fijian Dollar': "FJ",
    'FKP-Falkland Pound': "FK",
    'GBP-British P Sterling': "GB",
    'GEL-Georgian Lari': "GE",
    'GHC-Ghanaian Cedi' : "GH",
    'GIP-Gibraltar Pound': "GI",
    'GMD-Gambian Dalasi': "GM",
    'GNF-Guinean Franc': "GN",
    'GTQ-Guatemalan Quetzal': "GT",
    'GYD-Guyanese Dollar': "GY",
    'HKD-Hong Kong Dollar': "HK",
    'HNL-Honduran Lempira': "HN",
    'HRK-Croatian Kuna': "HR",
    'HTG-Haitian Gourde': "HT",
    'HUF-Hungarian Forint': "HU",
    'IDR-Indonesian Rupiah': "ID",
    'ILS-Israeli Shekel': "IL",
    'INR-Indian Rupee': "IN",
    'IQD-Iraqi Dinar': "IQ",
    'IRR-Iranian Rial': "IR",
    'ISK-Icelandic Króna': "IS",
    'JMD-Jamaican Dollar': "JM",
    'JOD-Jordanian Dinar': "JO",
    'JPY-Japanese Yen': "JP",
    'KES-Kenyan Shilling': "KE",
    'KGS-Kyrgyzstani Som': "KG",
    'KHR-Cambodian Riel': "KH",
    'KMF-Comorian Franc': "KM",
    'KPW-North Korean Won': "KP",
    'KRW-South Korean Won': "KR",
    'KWD-Kuwaiti Dinar': "KW",
    'KYD-Cayman Islands Dollar': "KY",
    'KZT-Kazakhstani Tenga': "KZ",
     'LAK-Laotian Kip': "LA",
  'LBP-Lebanese Pound': "LB",
  'LKR-Sri Lankan Rupee': "LK",
  'LRD-Liberian Dollar': "LR",
  'LSL-Lesotho Loti': "LS",
  'LYD-Libyan Dinar': "LY",
  'MAD-Moroccan Dirham': "MA",

  'MDL-Moldovan Leu': "MD",
  'MGA-Malagasy Ariary': "MG",
  'MKD-Macedonian Denar': "MK",
  'MMK-Myanmar Kyat': "MM",
  'MNT-Mongolian Tugrik': "MN",
  'MOP-Macanese Pataca': "MO",
  'MRO-Mauritanian Ouguiya': "MR",
  'MUR-Mauritian Rupee': "MU",
  'MVR-Maldivian Rufiyaa': "MV",
  'MWK-Malawian Kwacha': "MW",
  'MXN-Mexican Peso': "MX",
  'MYR-Malaysian Ringgit': "MY",
  'MZN-Mozambican Metical': "MZ",
  'NAD-Namibian Dollar': "NA",
  'NGN-Nigerian Naira': "NG",
  'NIO-Nicaraguan Córdoba': "NI",
  'NOK-Norwegian Krone': "NO",
  'NPR-Nepalese Rupee': "NP",
  'NZD-New Zealand Dollar': "NZ",
  'OMR-Omani Rial': "OM",
  'PAB-Panamanian Balboa': "PA",
  'PEN-Peruvian Sol': "PE",
  'PGK-Papua Kina': "PG",
  'PHP-Philippine Peso': "PH",
  'PKR-Pakistani Rupee': "PK",
  'PLN-Polish Złoty': "PL",
  'PYG-Paraguayan Guarani': "PY",
  'QAR-Qatari Riyal': "QA",
  'RON-Romanian Leu': "RO",
  'RSD-Serbian Dinar': "RS",
  'RUB-Russian Ruble': "RU",
  'RWF-Rwandan Franc': "RW",
  'SAR-Saudi Riyal': "SA",
  'SBD-Solomon Dollar': "SB",
  'SCR-Seychellois Rupee': "SC",
  'SDG-Sudanese Pound': "SD",
  'SEK-Swedish Krona': "SE",
  'SGD-Singapore Dollar': "SG",
  'SHP-Saint H Pound': "SH",
  'SLL-Sierra Leonean': "SL",
  'OS-Somali Shilling': "SO",
  'SRD-Surinamese Dollar': "SR",
  'SSP-South S Pound': "SS",
  'STD-São Tomé Dobra': "ST",
  'SVC-Salvadoran Colón': "SV",
  'SYP-Syrian Pound': "SY",
  'SZL-Swazi Lilangeni': "SZ",
  'THB-Thai Baht': "TH",
  'TJS-Tajikistani Somoni': "TJ",
  'TMT-Turkmenistani Manat': "TM",
  'TND-Tunisian Dinar': "TN",
  'TOP-Tongan Paanga': "TO",
  'TRY-Turkish Lira': "TR",
  'TTD-Trinidad  Dollar': "TT",
  'TVD-Tuvaluan Dollar': "TV",
  'UAH-Ukrainian Hryvnia': "UA",
  'UGX-Ugandan Shilling': "UG",
  'USD-US Dollar': "US",
  'UYU-Uruguayan Peso': "UY",
  'UZS-Uzbekistani Sums': "UZ",
  'VEF-Venezuelan Bolívar': "VE",
  'VES-Venezuelan Fuerte': "VE",
  'VND-Vietnamese Đồng': "VN",
  'VUV-Vanuatu Vatu': "VU",
  'WST-Samoan Tala': "WS",
  'XAF-CFA Franc BEAC': "CM",
  'XCD-Eastern  Dollar': "XC",
  'XOF-CFA Franc BCEAO': "CI",
  'XPF-CFP Franc': "PF",
  'YER-Yemeni Rial': "YE",
  'ZAR-South African Rand': "ZA",
  'ZMW-Zambian Kwacha': "ZM",
  'ZWL-Zimbabwean Dollar': "ZW",
};



 